name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
jobs:
  build:
    name: Build    
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,name=iPhone 11"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'
        additional_lint_params: --private
