name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
jobs:
  build:
    name: Build    
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,name=iPhone 11"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: CocoaPod Install
      run: pod install
    - name: Build
      run: xcodebuild -workspace RickAndMortyFinalApp.xcworkspace -scheme RickAndMortyFinalApp -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'        
