name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.app/Contents/Developer
      MINT_PATH: ${{ github.workspace }}/mint
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11']#
    steps:
     - name: Prepare iOS 12 simulator
       run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 12.4.simruntime
          xcrun simctl list runtimes
          xcrun simctl create custom-test-device "iPhone 11" "com.apple.CoreSimulator.SimRuntime.iOS-12-4"
          xcrun simctl list devices 12.4
     - name: Force Xcode 13
       run: sudo xcode-select -switch /Applications/Xcode_13.app
     - name: Checkout
       uses: actions/checkout@main
     - uses: actions/setup-ruby@v1
       with:
        ruby-version: '2.6'
     - name: Install pods
       run: pod install --repo-update
     - name: Build
       run: |
          xcodebuild clean build -workspace RickAndMortyFinalApp.xcworkspace -scheme RickAndMortyFinalApp -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          xcrun simctl list
       env: 
         destination: ${{ matrix.destination }}
     - name: Test
       run: |
          xcodebuild clean test -workspace RickAndMortyFinalApp.xcworkspace -scheme RickAndMortyFinalApp -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
       env: 
         destination: ${{ matrix.destination }}
